name: umusic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  dio: ^5.9.1
  youtube_explode_dart: ^2.5.3
  shared_preferences: ^2.5.4
  flutter_local_notifications: ^20.1.0
  permission_handler: ^12.0.1
  flutter_inappwebview: ^6.1.5
  webview_flutter: ^4.10.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  system_tray: ^2.0.3
  flutter_svg: ^2.2.3
  file_picker: ^10.3.10
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  get: ^4.7.3
  video_player: ^2.11.0
  chewie: ^1.13.0
  pod_player: ^0.2.2
  video_thumbnail: ^0.5.3
  just_audio: ^0.9.43
  audio_service: ^0.18.17
  just_audio_background: ^0.0.1-beta.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.svg
